### ISSUE TITLE
Fails at PHP require

### ISSUE THREAD

**Issue by jdittrich** [wmde/software.wikimedia.de#1]
**Story:** As a PHP allergic UX I want to see the webpage
**Problem:** I start the server on the command line with `php -S 0:8000` I get `PHP 7.0.13-0ubuntu0.16.04.1 Development Server started` (fine). If I go to the URI 0:8000, I get the following error: 
```PHP Warning:  require_once([STRIPPED FOLDERS]/software.wikimedia.de/web/../vendor/autoload.php): failed to open stream: No such file or directory in [STRIPPED FOLDERS]/software.wikimedia.de/web/index.php on line 7```
(Stripped folders = lengthy path to the repo folder)

**Comment by JeroenDeDauw** [comment]
Cause you did not run `composer install`
