### ISSUE TITLE
Our Department

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#10]
Could you please link on this site: https://www.mediawiki.org/wiki/WMDE_Engineering
So this is the Landingpage

**Comment by JeroenDeDauw** [comment]
DO I understand correctly that you are talking about this link?

![link](https://cloud.githubusercontent.com/assets/146040/22869691/2d9065f2-f1a1-11e6-90e3-d840a8a908ab.png)

We already have a stub page at https://software.wikimedia.de/department. I'd rather migrate the content from MediaWiki.org than link there from the homepage.

I'd be great if you could outline what you think we should have for new pages and what should be on those to migrate the content we have not gotten to yet.

**Comment by JeroenDeDauw** [comment]
Please reopen if still relevant now we have a department page
