### ISSUE TITLE
[Jobs] Add HoSDE 

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#22]
Adding https://wikimedia.de/wiki/Head_of_Software_Development_%26_Engineering_(f/m)
on the website

**Comment by JeroenDeDauw** [comment]
> We're offering part-time and remote opportunities. Please send your application to jobs@wikimedia.de, mentioning your earliest date of entry and your salary presentation to our person, Mrs. Natali Bosnjakovic.

wtf? Is that a mistake? Or are we really fine with a remote head of department?

**Comment by JeroenDeDauw** [comment]
I left out that sentence... let me know if it needs to be added again in some form
