### ISSUE TITLE
[Jobs] Add Fullstack Freelancer/Contractor 

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#23]
https://wikimedia.de/wiki/Software_Engineer_with_focus_on_Full_Stack_Development_-_Senior_(m/f)_freelancer

**Comment by JeroenDeDauw** [comment]
Is that the same as the existing https://software.wikimedia.de/jobs/fullstack-developer with the only difference being that this is freelance? If so, perhaps we can mention on the page it is possible to apply both as freelance and as "real job"?

If I'm not mistaken you wanted to add another section to https://software.wikimedia.de/jobs linking to the same page some weeks ago but then for some reason did not do so. That was for this position no?

**Comment by JeroenDeDauw** [comment]
Ping @samu-wmde

**Comment by samu-wmde** [comment]
So the Job is really flexible. It's also offered as freelance job, because that could be more attractive for people to apply. So it's one job with two options.
