### ISSUE TITLE
Jobs HoSDE insert right membership & employee data 

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#26]
Need to be changed: 
85 employees and 50.000 members

**Comment by JeroenDeDauw** [comment]
wtf? I changed it to 35k in https://github.com/wmde/software.wikimedia.de/commit/3590709b7b2695c6193a8c4875bad60d4c3ff053#diff-040eaf60e96274c95330f4307ae55a77 cause in the UX profile it was changed FROM 50k to 35k... So if I change it to 50k again, that correction is undone.
