### ISSUE TITLE
Jobs: UX Intern 

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#3]
Please insert Job Description UX Intern:
https://docs.google.com/document/d/1KQYGW4lH1dAxGcpjvElqx7Xi7Xc9bWOb28sxPzn7Gjw/edit

**Comment by JeroenDeDauw** [comment]
Done: https://software.wikimedia.de/jobs/ux-intern

**Comment by JeroenDeDauw** [comment]
@jdittrich you and Nose might want to double check everything is fluff

Content here is case you want to make a PR: https://github.com/wmde/software.wikimedia.de/blob/master/app/templates/pages/jobs/ux-intern.html
