### ISSUE TITLE
Such issues

### ISSUE THREAD

**Issue by Incabell** [wmde/software.wikimedia.de#31]
@JeroenDeDauw 
such question mark
![such a question mark](https://cloud.githubusercontent.com/assets/2711781/23795846/f5437c88-0597-11e7-84f4-74374eae6a92.PNG)

The (intern) under Julias image is wrong, Michi is missing, and Daniel and Birgit should also be in the department wide category if I'm not mistaken.

**Comment by jakobw** [comment]
I'm missing too :[

**Comment by Ladsgroup** [comment]
As well as Leszek. Not sure about Katie and me (contractors)

**Comment by Incabell** [comment]
oh yeah. Sorry... I thought I spotted everyone :(

**Comment by JeroenDeDauw** [comment]
Sorry for who is missing... I just put in people from a list someone hand typed and did not do a comprehensive check yet. You can easily add yourself: https://github.com/wmde/software.wikimedia.de/blob/master/app/templates/pages/department.html#L80

Contractors are not on https://wikimedia.de/wiki/Mitarbeiter... I suppose it's still fine to list them though.

As to the layout issue... idk why this happens. I noticed it before and moved stuff so it does not happen on most screen resolutions. Such UX wizards fix it? :)

**Comment by JeroenDeDauw** [comment]
Please do create one ticket per issue and give it a proper name.

**Comment by JeroenDeDauw** [comment]
I've now created dedicated tickets.

**Comment by manicki** [comment]
> Contractors are not on https://wikimedia.de/wiki/Mitarbeiter... I suppose it's still fine to list them though.

I am sure @samu-wmde will say something on this when she has time but IIRC there was some thing related to listing contractors as employees vs German law. Not saying this applies here ("Our teams" could mean something else than "Staff" on the other site, and I'd personally would be happy to have Katie and Amir listed on this site), just mentioning something I hope is relevant here.

**Comment by JeroenDeDauw** [comment]
Create a new issue?
