### ISSUE TITLE
Figure out where Birgit and Daniel should be

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/software.wikimedia.de#34]
> Daniel and Birgit should also be in the department wide category -- @Incabell

**Comment by JeroenDeDauw** [comment]
I put them in the teams they are in as per list I got by @samu-wmde. So clarification is needed before any changes are made here by me. Feel free to create a PR though.

**Comment by jdittrich** [comment]
Remark: No matter how we structure this, please keep in mind that people who look at the page are probably interested in who-works-on-what; we should not care to replicate our orgchart here.

**Comment by JeroenDeDauw** [comment]
The main reason for creating this site is recruiting. To advertise ourselves and to give people an idea of what our organization looks like. Common questions include how many teams we have and how big they are. This is the reason we have the teams first, and the rest of the people all together in a bucket at the bottom, rather than starting with "Department Head", "Second in Command", etc.

**Comment by jdittrich** [comment]
> If you think we should also cater to another usecase please describe it (in a new issue).
No, what you described seemed be a pretty good main usecase and reasoning for me.
