### ISSUE TITLE
Design: Header

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#4]
Please change the transparent block in the backround of Wikimedia Deutschland Software Development Department. Having something transparent behind the Wikimedia Logo is not align with the Logo / Graphic Policy of the WMF.

**Comment by JeroenDeDauw** [comment]
This amuses me :) One thing one by our UI experts and one UI complaint which is about that thing :) Without the box [*] the logo is not well visible. I think UX did a great job fixing that.

Ping @jdittrich

[*] This is the real reason behind this issue right? You just want to kill the box! :(

**Comment by samu-wmde** [comment]
No this is not Jan who suggested it. It was the press office. There also
two other issues

Am 01.02.2017 7:48 nachm. schrieb "Jeroen De Dauw" <notifications@github.com

**Comment by JeroenDeDauw** [comment]
Such a confoose. What I'm saying is that @jdittrich created the box to solve the logo not showing well on the postcard background. I could remove the box but then the thing is going to look quite bad.

> There also two other issues

Well create an issue for each then please

**Comment by jdittrich** [comment]
Sorry, I oversaw this...
Let’s make the transparent box white and the logo black. We can do this tomorrow or so.

**Comment by jdittrich** [comment]
So, did the changes and put them into a [LogoNoTransparent](https://github.com/wmde/software.wikimedia.de/tree/logoNoTransparent)-branch. It would do fine on paper, but on screen this contrast of bigger black/white areas is pretty harsh.

**Comment by jdittrich** [comment]
…also, after talking with KOM, it seems to be OK to use the logo on an image. Also, the styleguide does not even say anything about the background. I am not allowed to make the logo itself transparent but it seems I can but it where ever I want (as long as it is reasonable).

**Comment by JeroenDeDauw** [comment]
Ping @samu-wmde

**Comment by JeroenDeDauw** [comment]
Closing as apparently this is not an actual issue. Please reopen if that is wrong
