### ISSUE TITLE
Non-clickable Icons should be gray (inactive), not black

### ISSUE THREAD

**Issue by jdittrich** [wmde/software.wikimedia.de#40]
![image](https://cloud.githubusercontent.com/assets/3416487/23851441/d61c2c26-07e3-11e7-9c72-440909ce85ac.png)
Icons which serve to trigger actions should be gray/visually inactive if they are not linked/used. In the case above this would be the globe icon (which should link to a webpage, I assume) but does not. So it should look like: 
![image](https://cloud.githubusercontent.com/assets/3416487/23851565/465d2abc-07e4-11e7-8b2b-5ac262181a74.png)

**Comment by JeroenDeDauw** [comment]
Is there a (sane) way of doing this without modifying the images? They come with font-awesome, and it's nice to not modify resources provided by libraries we use.

**Comment by KaiNissen** [comment]
Those are not images, but "characters". We can just add a class for these to our (already) customized CSS and use that in the markup, right?

**Comment by thiemowmde** [comment]
I suggest to simply remove non-functional icons. Let's not make this more complicated than it needs to be.

**Comment by jdittrich** [comment]
@KaiNissen: If it is font-awesome, yes, we just need to add something like
"fa-disabled" to the classlist for icons (they are used like `<i class="fa fa-2x fa-envelope-square"></i>`)

@thiemowmde: Yes. We could mark them "hidden" in the CSS.

**Comment by thiemowmde** [comment]
@jdittrich: I meant, just remove the empty snippets of HTML that create these dysfunctional icons.

**Comment by jdittrich** [comment]
@thiemowmde: We could, but that would make their positions change. I would need to try both visually to find what is better: No gaps (but sometimes changing position for the icons) or gaps (but mail icon is at the same position in each rectangle)

**Comment by thiemowmde** [comment]
What gaps? The icons are not aligned in a table. It's just that some people have two icons, while others have three.

**Comment by jdittrich** [comment]
Yes – I said gaps and "like in a table" *might* be preferable, since the same icon would always be in the same place
