### ISSUE TITLE
Tackle deployment bottleneck

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/software.wikimedia.de#41]
Context: the site is run on some WMDE server managed by IT. The "deployment process" is ssh'ing into the box and executing `git pull` in `~/html`, possibly followed by a `php composer.phar update`.

Right now I am the only one of the software department that has access, via a personal ssh account. While everyone can change the canonical version of the sites source here on GitHub, it requires action from my side to deploy. Removing the dependence on me would be good, and perhaps we could have some form of automation.

Given the current development status of the site this does not seem to warrant much effort. That might change, and perhaps there is an easy way of solving this issue.

**Comment by addshore** [comment]
> Right now I am the only one of the software department that has access, via a personal ssh account.

Is it possible to add more accounts?

**Comment by JeroenDeDauw** [comment]
It should be... just poke IT

**Comment by addshore** [comment]
> It should be... just poke IT

I have poked :)

**Comment by addshore** [comment]
I now also have access to this hosting, so a slightly smaller bottleneck, but still a bottleneck!

**Comment by JeroenDeDauw** [comment]
Good enough for now I think
