### ISSUE TITLE
Provide section for the Community Communication and UX team

### ISSUE THREAD

**Issue by jdittrich** [wmde/software.wikimedia.de#51]
Shall we create a section for the community communications team and UX to reflect the formal team structures? (See [current department page](https://software.wikimedia.de/department), asking @samu-wmde, @johl )

**Comment by JeroenDeDauw** [comment]
Please beware that the page is not intended to be formal. As it says on the page itself:

> What follows is an informal approximation of our teams. It is not an org-chart and it does not capture all the details of peoples responsibilities, though should still give you a good idea of how out department is structured. 

At present I think the page does a good job indicating that the UX people are not a dev team, and instead have a department wide role. Whatever you do, it'd be good to retain that aspect.

**Comment by jdittrich** [comment]
thx
