### ISSUE TITLE
Add explanation of the hiring process

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/software.wikimedia.de#53]
Outline the hiring process on the jobs page

**Comment by JeroenDeDauw** [comment]
I found an example that does this in pretty much the exact same way as I was thinking about :0 https://codurance.com/careers/

**Comment by lydiapintscher** [comment]
I think as it is that is very developer focused. There is a sentence hidden at the bottom that says it is slightly different for other positions. I don't think this is good enough.

There is also something wrong with the layout:
![spectacle z25447](https://user-images.githubusercontent.com/550412/27911707-4c0ff432-625a-11e7-9be0-a1f1d0cf28e6.png)

**Comment by JeroenDeDauw** [comment]
It is definitely dev specific. I've moved up the line indicating that to before the steps.

Layout issue tracked at https://github.com/wmde/software.wikimedia.de/issues/60
