### ISSUE TITLE
Allow for contact detail submission

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/software.wikimedia.de#54]
ie a "send me info whenever a new job becomes available".

Motivation: right now we miss out on potential good candidates whenever we don't have a suitable job for them at the time they view the site. This forces us to start looking for candidates from scratch when a position becomes available rather than already having a pool of interested people.

**Comment by gbirke** [comment]
For a MVP, a `mailto:` link might be better than nothing. Someone™️ should talk to Sandra/Linda about that. Maybe they have a mail address for that.

**Comment by manicki** [comment]
Closing as this site is being shut down.
