### ISSUE TITLE
Career Opportunities: Changing text 

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#6]
Please replace in every jobposting the following paragraph: 

"about 80 employees and 50.000 member" instead of "... than 80 employees and about 35.000 members ..."

**Comment by JeroenDeDauw** [comment]
I already did this when I put the UX Intern in there. On the new site this description only exists once and is used on all job pages, so it is no longer (and can no longer be) inconsistent.

https://github.com/wmde/software.wikimedia.de/blob/master/app/templates/job-layout.html#L23-L27
