### ISSUE TITLE
Layout issue on jobs page

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/software.wikimedia.de#60]
![spectacle z25447](https://user-images.githubusercontent.com/550412/27911707-4c0ff432-625a-11e7-9be0-a1f1d0cf28e6.png)

**Comment by JeroenDeDauw** [comment]
@lydiapintscher how to reproduce this? Not seeing anything wrong using FireFox or Chromium.

**Comment by lydiapintscher** [comment]
Hmmm I am looking at it in Chromium. I don't think there is anything special I have that would cause it.

**Comment by lydiapintscher** [comment]
Ah now it looks better after your latest change:
![spectacle b28652](https://user-images.githubusercontent.com/550412/27915820-a18881b0-6267-11e7-8ed5-33ae4d85fa06.png)

**Comment by JeroenDeDauw** [comment]
Huh... but the dot is still there. Or is that part of your screenshot thing?

**Comment by lydiapintscher** [comment]
*lol*
I thought that part was intentional. I mostly have the gray stripe in mind that goes over the text in the first screenshot.

**Comment by JeroenDeDauw** [comment]
That part is now tracked as https://github.com/wmde/software.wikimedia.de/issues/61
