### ISSUE TITLE
Job application timeline UI issue

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/software.wikimedia.de#61]
As reported by @lydiapintscher 

![spectacle b28652](https://user-images.githubusercontent.com/550412/27915820-a18881b0-6267-11e7-8ed5-33ae4d85fa06.png)

This is on https://software.wikimedia.de/jobs

Issue: in Lydia's browser a dot is displayed on the left side that should not be there and the box is not on the line itself. Not happening for me on either FireFox or Chromium:

![screenshot_20170707_082011](https://user-images.githubusercontent.com/146040/27945428-3940ac46-62ed-11e7-9d20-9aa22d43159d.png)

**Comment by JeroenDeDauw** [comment]
Looks good on mobile as well for me

**Comment by gbirke** [comment]
Looks good on iOS (iPhone), there are no dots (or squares) at all.

**Comment by manicki** [comment]
Closing as this site is being shut down.
