### ISSUE TITLE
Projects: Fundraising

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#8]
You can use this picture as logo for the fundraising campaign: 
https://commons.wikimedia.org/wiki/File:HK15_topbanner_blue_2015_Ctrl.PNG?uselang=de

**Comment by JeroenDeDauw** [comment]
Eh, the dimensions of that are really not good. It's way wider than it is high.

Ping @gbirke @KaiNissen this is for https://software.wikimedia.de/projects

**Comment by samu-wmde** [comment]
Fundraising has no logo :(

**Comment by JeroenDeDauw** [comment]
Presumably we could use a picture of the donation form...

**Comment by JeroenDeDauw** [comment]
Done by https://github.com/wmde/software.wikimedia.de/commit/7756432b7f0c0b9ecf1ffe4085353b91fad9348b
