### ISSUE TITLE
Sort dev blog posts by date

### ISSUE THREAD

**Issue by addshore** [wmde/software.wikimedia.de#81]
Instead of by developer (line added by Jeroen)

https://github.com/wmde/software.wikimedia.de/blob/master/app/templates/pages/department.html#L556

**Comment by JeroenDeDauw** [comment]
When poking at this, keep in mind the multiple HTTP requests being made. Right now with the super simple solution the page takes two or 3 seconds to load when it is not in the cache, so lots of room for improvement there.

**Comment by manicki** [comment]
Closing as this site is being shut down.
