### ISSUE TITLE
Data Protection Information to add in the Imprint

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#83]
Data protection

At www.wikimedia.de/imprint you will find all information about what happens with your personal data when you visit this website or other websites of Wikimedia Deutschland.

**Comment by JeroenDeDauw** [comment]
Is what should happen here a change of the Imprint link from `https://wikimedia.de/wiki/Kontakt#impressum` to `https://www.wikimedia.de/impressum`?

**Comment by samu-wmde** [comment]
Yes.

**Comment by samu-wmde** [comment]
Its the wrong one. It links now to: https://wikimedia.de/wiki/Kontakt#datenschutz. It should link to: https://wikimedia.de/de/impressum

**Comment by manicki** [comment]
when I open the page, the link at the bottom of the page, the one saying Impressum, links to: https://wikimedia.de/en/imprint
Is this what you mean @samu-wmde ?
If you have the old link, maybe it is the matter of browser cache and CTRL+F5 fixes it?

**Comment by samu-wmde** [comment]
Add https://wikimedia.de/en/imprint also to Datenschutz

**Comment by manicki** [comment]
Requirements changed, from email:
> Can you call it Impressum & datenschutz

**Comment by samu-wmde** [comment]
Great thanks

Leszek Manicki <notifications@github.com> schrieb am Fr., 25. Mai 2018,
12:30:
